#!/usr/bin/env python3
"""Generate public, aggregate portfolio performance data from a Trading 212 CSV."""
import csv, json, sys, urllib.parse, urllib.request
from datetime import datetime, timedelta
from pathlib import Path

SYMBOLS = {
 "META":("META","USD"),"GOOGL":("GOOGL","USD"),"ASML":("ASML.AS","EUR"),"IONQ":("IONQ","USD"),
 "SYM":("SYM","USD"),"RHM":("RHM.DE","EUR"),"NEE":("NEE","USD"),"ABNB":("ABNB","USD"),
 "O":("O","USD"),"BRK.B":("BRK-B","USD"),"QQQA":("QQQA.L","GBX"),"VUAG":("VUAG.L","GBP"),
 "SGLN":("SGLN.L","GBX"),"MSFT":("MSFT","USD"),"SPCX":("SPCX","USD"),"PSH":("PSH.L","GBX"),"HOOD":("HOOD","USD")}

def history(symbol, start, end):
    p1=int(datetime.fromisoformat(start).timestamp()); p2=int((datetime.fromisoformat(end)+timedelta(days=2)).timestamp())
    url=f"https://query1.finance.yahoo.com/v8/finance/chart/{urllib.parse.quote(symbol)}?period1={p1}&period2={p2}&interval=1d&events=div%2Csplits"
    req=urllib.request.Request(url,headers={"User-Agent":"Mozilla/5.0"})
    with urllib.request.urlopen(req) as response: result=json.load(response)["chart"]["result"][0]
    closes=result["indicators"]["quote"][0]["close"]
    return {datetime.fromtimestamp(t).date().isoformat():c for t,c in zip(result["timestamp"],closes) if c is not None}

def ff(series, day):
    keys=[k for k in series if k<=day]
    return series[max(keys)] if keys else None

def main():
    csv_path=Path(sys.argv[1]); out=Path(sys.argv[2] if len(sys.argv)>2 else "src/data/portfolioPerformance.generated.ts")
    with csv_path.open(encoding="utf-8-sig") as f: rows=list(csv.DictReader(f))
    rows.sort(key=lambda r:r["Time"]); start=rows[0]["Time"][:10]; end=datetime.now().date().isoformat()
    prices={t:history(y,start,end) for t,(y,_) in SYMBOLS.items()}
    prices["GBPUSD"]=history("GBPUSD=X",start,end); prices["EURGBP"]=history("EURGBP=X",start,end)
    positions={}; cash=0.; executions={}; events={}
    for r in rows: events.setdefault(r["Time"][:10],[]).append(r)
    days=[]; d=datetime.fromisoformat(start).date(); finish=datetime.now().date()
    while d<=finish:
        ds=d.isoformat()
        for r in events.get(ds,[]):
            action=r["Action"]; total=float(r["Total"] or 0); ticker=r["Ticker"]
            if action=="Deposit": cash+=total
            elif "buy" in action.lower():
                shares=float(r["No. of shares"]); cash-=total; positions[ticker]=positions.get(ticker,0)+shares; executions[ticker]=float(r["Price / share"])
            elif "sell" in action.lower():
                shares=float(r["No. of shares"]); cash+=total; positions[ticker]=positions.get(ticker,0)-shares
            elif action.startswith("Dividend") or action=="Interest on cash": cash+=total
        if d.weekday()<5:
            invested=0.
            for ticker,shares in positions.items():
                if abs(shares)<1e-9: continue
                price=ff(prices[ticker],ds) or executions[ticker]; currency=SYMBOLS[ticker][1]
                if currency=="USD": value=price/ff(prices["GBPUSD"],ds)
                elif currency=="EUR": value=price*ff(prices["EURGBP"],ds)
                elif currency=="GBX": value=price/100
                else: value=price
                invested+=shares*value
            bench=ff(prices["VUAG"],ds)
            if bench: days.append({"date":ds,"portfolio":round(cash+invested,2),"benchmarkClose":bench})
        d+=timedelta(days=1)
    initial=1999.; base=days[0]["benchmarkClose"]
    for p in days: p["benchmark"]=round(initial*p.pop("benchmarkClose")/base,2)
    weekly=[]
    for p in days:
        key=datetime.fromisoformat(p["date"]).strftime("%G-W%V")
        if weekly and weekly[-1][0]==key: weekly[-1]=(key,p)
        else: weekly.append((key,p))
    weekly=[p for _,p in weekly]
    peak=days[0]["portfolio"]; max_dd=0
    for p in days: peak=max(peak,p["portfolio"]); max_dd=min(max_dd,p["portfolio"]/peak-1)
    latest=days[-1]; pr=(latest["portfolio"]/initial-1)*100; br=(latest["benchmark"]/initial-1)*100
    payload={"daily":days,"weekly":weekly,"summary":{"asOf":latest["date"],"startingValue":initial,"portfolioValue":latest["portfolio"],"cash":round(cash,2),"portfolioReturn":round(pr,2),"benchmarkReturn":round(br,2),"relativeReturn":round(pr-br,2),"maxDrawdown":round(max_dd*100,2)}}
    out.parent.mkdir(parents=True,exist_ok=True)
    out.write_text("// Generated by scripts/generate-portfolio-performance.py; aggregate values only.\nexport const portfolioPerformance = "+json.dumps(payload,separators=(",",":"))+" as const;\n",encoding="utf-8")
    print(f"Wrote {len(days)} daily and {len(weekly)} weekly observations to {out}")

if __name__=="__main__": main()
